/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Soumettre un texte à analyser */
        post: operations["creer_analyse_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analyse_id}/statut": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulter le statut d'une analyse */
        get: operations["obtenir_statut_analyse_analyses__analyse_id__statut_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/connexion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Se connecter */
        post: operations["connexion_auth_connexion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/deconnexion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Se déconnecter */
        post: operations["deconnexion_auth_deconnexion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/inscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Créer un compte */
        post: operations["inscription_auth_inscription_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rafraîchir la paire de jetons */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compte": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulter son compte */
        get: operations["consulter_compte_compte_get"];
        put?: never;
        post?: never;
        /** Supprimer son compte */
        delete: operations["supprimer_compte_compte_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/historique": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulter son historique personnel */
        get: operations["lister_historique_historique_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalyseEnAttenteReponse
         * @description Réponse `202` — le résultat n'est pas encore prêt, le client poll
         *     `GET /analyses/{id}/statut` (D5) avec ce `job_id`.
         * @example {
         *       "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
         *     }
         */
        AnalyseEnAttenteReponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /**
         * AnalyseRequete
         * @example {
         *       "source_type": "github",
         *       "texte": "Contribue surtout à des side-projects Python le week-end, jamais de PR le vendredi soir."
         *     }
         */
        AnalyseRequete: {
            source_type: components["schemas"]["SourceAnalyse"];
            /** Texte */
            texte: string;
        };
        /**
         * AnalyseTermineeReponse
         * @description Réponse `200` de `POST /analyses` — le résultat est immédiatement
         *     disponible (cache-hit, ou première génération déjà terminée avant que
         *     ce ticket ne branche le job asynchrone réel, voir F1).
         *
         *     Réutilisée telle quelle comme réponse de `GET /analyses/{id}/statut`
         *     (D5) : c'est exactement la forme `pending | done | failed (+ résultat
         *     si done)` demandée par ce ticket, `statut` portant `PENDING`/`FAILED`
         *     avec les deux champs résultat à `None` dans ces cas.
         * @example {
         *       "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "resultat_image_url": "https://cdn.example.com/images/3fa85f64.png",
         *       "resultat_texte": "Un profil qui code le week-end mais respecte son vendredi soir.",
         *       "statut": "done"
         *     }
         */
        AnalyseTermineeReponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Resultat Image Url */
            resultat_image_url: string | null;
            /** Resultat Texte */
            resultat_texte: string | null;
            statut: components["schemas"]["StatutAnalyse"];
        };
        /**
         * ConnexionRequete
         * @example {
         *       "email": "ada@example.com",
         *       "mot_de_passe": "trombone-cheval-9"
         *     }
         */
        ConnexionRequete: {
            /** Email */
            email: string;
            /** Mot De Passe */
            mot_de_passe: string;
        };
        /**
         * DeconnexionRequete
         * @example {
         *       "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
         *     }
         */
        DeconnexionRequete: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * EntreeHistoriqueReponse
         * @example {
         *       "created_at": "2026-08-18T10:00:00Z",
         *       "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *       "input_text": "Contribue surtout à des side-projects Python le week-end.",
         *       "resultat_id": "7c9e6679-7425-40de-944b-e07fc1f90ae7"
         *     }
         */
        EntreeHistoriqueReponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input Text */
            input_text: string;
            /**
             * Resultat Id
             * Format: uuid
             */
            resultat_id: string;
        };
        /**
         * ErreurAPI
         * @description Format de réponse unique pour toute erreur API (agents.md §3, §9).
         *
         *     `code` est un identifiant stable destiné aux clients (jamais le message,
         *     qui peut changer sans préavis) ; `correlation_id` permet de retrouver la
         *     requête dans les logs structurés (shared/logging.py).
         */
        ErreurAPI: {
            /** Code */
            code: string;
            /** Correlation Id */
            correlation_id: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoriquePageReponse
         * @example {
         *       "items": [
         *         {
         *           "created_at": "2026-08-18T10:00:00Z",
         *           "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
         *           "input_text": "Contribue surtout à des side-projects Python le week-end.",
         *           "resultat_id": "7c9e6679-7425-40de-944b-e07fc1f90ae7"
         *         }
         *       ],
         *       "page": 1,
         *       "page_size": 20,
         *       "total": 1
         *     }
         */
        HistoriquePageReponse: {
            /** Items */
            items: components["schemas"]["EntreeHistoriqueReponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * InscriptionRequete
         * @example {
         *       "email": "ada@example.com",
         *       "mot_de_passe": "trombone-cheval-9"
         *     }
         */
        InscriptionRequete: {
            /** Email */
            email: string;
            /** Mot De Passe */
            mot_de_passe: string;
        };
        /**
         * JetonsReponse
         * @example {
         *       "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
         *       "expires_in": 900,
         *       "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
         *       "token_type": "bearer"
         *     }
         */
        JetonsReponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Refresh Token */
            refresh_token: string;
            /** Token Type */
            token_type: string;
        };
        /**
         * RafraichissementRequete
         * @example {
         *       "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
         *     }
         */
        RafraichissementRequete: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * SourceAnalyse
         * @description Catégorie du texte source collé par l'user (projets.md §1 : profil
         *     GitHub, historique d'écoute, bio, ou tout autre texte libre).
         *
         *     Vocabulaire du domaine Analyse (D1) — distincte de `SourceType`
         *     (modules/cache/adaptateurs/models.py), qui est le type de persistance
         *     de la table `cache_resultat` (B6). Le mapping entre les deux est un
         *     détail de l'adaptateur `CachePort` (D2), jamais une préoccupation du
         *     domaine (agents.md §4 : le port ne connaît pas la techno).
         * @enum {string}
         */
        SourceAnalyse: "github" | "spotify" | "bio" | "autre";
        /**
         * StatutAnalyse
         * @description Statut du cycle de vie d'une analyse, piloté par l'algorithme de
         *     concurrence du cache exact (projets.md §Concurrence sur le cache) :
         *     `PENDING` posé par le premier appelant, puis transitionné vers `DONE`
         *     ou `FAILED` une fois le job de génération terminé (D3).
         * @enum {string}
         */
        StatutAnalyse: "pending" | "done" | "failed";
        /**
         * SuppressionCompteRequete
         * @description Redemande le mot de passe (vérification renforcée, H3, agents.md §7).
         * @example {
         *       "mot_de_passe": "trombone-cheval-9"
         *     }
         */
        SuppressionCompteRequete: {
            /** Mot De Passe */
            mot_de_passe: string;
        };
        /**
         * UtilisateurReponse
         * @description Ne reprend jamais `password_hash` : un hash n'a rien à faire dans une réponse API.
         * @example {
         *       "created_at": "2026-08-18T10:00:00Z",
         *       "email": "ada@example.com",
         *       "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
         *     }
         */
        UtilisateurReponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    creer_analyse_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyseRequete"];
            };
        };
        responses: {
            /** @description `200` si le résultat est déjà en cache (contenu identique déjà analysé), `202` avec un `job_id` si la génération vient d'être déclenchée — à poller via `GET /analyses/{id}/statut`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyseTermineeReponse"] | components["schemas"]["AnalyseEnAttenteReponse"];
                };
            };
            /** @description Texte vide, uniquement composé d'espaces, ou dépassant 5000 caractères. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "entree_invalide",
                     *       "correlation_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "message": "Le texte à analyser ne peut pas être vide."
                     *     }
                     */
                    "application/json": components["schemas"]["ErreurAPI"];
                };
            };
            /** @description Quota dépassé (par IP pour un appelant anonyme, par compte pour un appelant authentifié) — message générique, ne révèle jamais le quota exact (agents.md §7). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "limite_debit_depassee",
                     *       "correlation_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "message": "Trop de requêtes, réessaie dans quelques instants."
                     *     }
                     */
                    "application/json": components["schemas"]["ErreurAPI"];
                };
            };
        };
    };
    obtenir_statut_analyse_analyses__analyse_id__statut_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analyse_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statut courant (`pending`/`done`/`failed`), résultat inclus si `done`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyseTermineeReponse"];
                };
            };
            /** @description Aucune analyse ne correspond à cet identifiant. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ressource_introuvable",
                     *       "correlation_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "message": "Aucune analyse ne correspond à cet identifiant."
                     *     }
                     */
                    "application/json": components["schemas"]["ErreurAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connexion_auth_connexion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnexionRequete"];
            };
        };
        responses: {
            /** @description Paire de jetons émise (access + refresh). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JetonsReponse"];
                };
            };
            /** @description Email ou mot de passe incorrect (message générique, agents.md §7 — ne distingue jamais email inconnu de mot de passe erroné). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "non_authentifie",
                     *       "correlation_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "message": "Email ou mot de passe incorrect."
                     *     }
                     */
                    "application/json": components["schemas"]["ErreurAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deconnexion_auth_deconnexion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeconnexionRequete"];
            };
        };
        responses: {
            /** @description Refresh token courant révoqué (toujours 204, même si déjà invalide — idempotent). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inscription_auth_inscription_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InscriptionRequete"];
            };
        };
        responses: {
            /** @description Compte créé. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UtilisateurReponse"];
                };
            };
            /** @description Un compte existe déjà avec cet email (message volontairement générique, agents.md §7 — pas d'énumération d'utilisateurs). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "conflit_ressource",
                     *       "correlation_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "message": "Impossible de créer le compte avec ces informations."
                     *     }
                     */
                    "application/json": components["schemas"]["ErreurAPI"];
                };
            };
            /** @description Email mal formé ou mot de passe jugé trop faible. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "entree_invalide",
                     *       "correlation_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "message": "Le mot de passe doit contenir entre 10 et 128 caractères."
                     *     }
                     */
                    "application/json": components["schemas"]["ErreurAPI"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RafraichissementRequete"];
            };
        };
        responses: {
            /** @description Nouvelle paire de jetons, dans la même famille de rotation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JetonsReponse"];
                };
            };
            /** @description Refresh token invalide, expiré, ou déjà utilisé — un rejeu détecté révoque toute la famille de jetons et force une reconnexion (agents.md §7). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "non_authentifie",
                     *       "correlation_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "message": "Refresh token invalide ou expiré."
                     *     }
                     */
                    "application/json": components["schemas"]["ErreurAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consulter_compte_compte_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Infos du compte de l'appelant authentifié. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UtilisateurReponse"];
                };
            };
            /** @description Aucun jeton présenté, jeton invalide/expiré, ou compte déjà supprimé. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "non_authentifie",
                     *       "correlation_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "message": "Authentification requise."
                     *     }
                     */
                    "application/json": components["schemas"]["ErreurAPI"];
                };
            };
        };
    };
    supprimer_compte_compte_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuppressionCompteRequete"];
            };
        };
        responses: {
            /** @description Compte, refresh tokens et historique personnel supprimés (cascade au niveau du schéma, B6). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié, ou mot de passe incorrect (message générique, agents.md §7 — même posture que /auth/connexion). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "non_authentifie",
                     *       "correlation_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "message": "Mot de passe incorrect."
                     *     }
                     */
                    "application/json": components["schemas"]["ErreurAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    lister_historique_historique_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page de l'historique de l'appelant authentifié, du plus récent au plus ancien. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoriquePageReponse"];
                };
            };
            /** @description Aucun jeton présenté, ou jeton invalide/expiré. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "non_authentifie",
                     *       "correlation_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "message": "Authentification requise."
                     *     }
                     */
                    "application/json": components["schemas"]["ErreurAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
