"""schema initial : user, cache_resultat, historique

Revision ID: 322c2ef784b8
Revises:
Create Date: 2026-08-12 20:20:16.347213

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "322c2ef784b8"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache_resultat",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("github", "spotify", "bio", "autre", name="source_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "done", "failed", name="statut_cache"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("output_text", sa.Text(), nullable=True),
        sa.Column("output_image_url", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("hit_count", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cache_resultat")),
    )
    op.create_index(
        op.f("ix_cache_resultat_input_hash"), "cache_resultat", ["input_hash"], unique=True
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "historique",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("resultat_id", sa.UUID(), nullable=False),
        sa.Column("input_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resultat_id"],
            ["cache_resultat.id"],
            name=op.f("fk_historique_resultat_id_cache_resultat"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_historique_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historique")),
    )
    op.create_index(op.f("ix_historique_resultat_id"), "historique", ["resultat_id"], unique=False)
    op.create_index(op.f("ix_historique_user_id"), "historique", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_historique_user_id"), table_name="historique")
    op.drop_index(op.f("ix_historique_resultat_id"), table_name="historique")
    op.drop_table("historique")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_cache_resultat_input_hash"), table_name="cache_resultat")
    op.drop_table("cache_resultat")
    # ### end Alembic commands ###
    # Alembic autogenerate ne le fait pas lui-même : `drop_table` supprime
    # les tables mais pas les types ENUM Postgres qu'elles référençaient,
    # ce qui casse un `upgrade` ultérieur (`CREATE TYPE` sur un type déjà
    # existant). Sans ce nettoyage explicite, le rollback n'est pas
    # vraiment réversible (agents.md §3 : stratégie de rollback attendue).
    sa.Enum(name="statut_cache").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="source_type").drop(op.get_bind(), checkfirst=False)
